name: level-1 CI
on:
  push:
    branches:
      - main
jobs:
  frist_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo Message
        run: echo "GitHub Actions connected successfully!"
