name: Level-2 CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64] # Ensure your runner labels are correct
    
    # 1. Define the Matrix Strategy
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11'] # The versions to test

    steps:
    - uses: actions/checkout@v4
    - name: ðŸŸ¢ Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        # 2. Use the variable here
        python-version: ${{ matrix.python-version }}

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirement.txt

    - name: Run tests
      run: |
          # Set PYTHONPATH to include the current directory (repo root)
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          # Now run pytest, which can find the 'app' module
          pytest

    - name: Upload result log
      uses: actions/upload-artifact@v4
      with:
        name: test-result
        path: .

